Added Riskified
disconnectme/disconnect-tracking-protection pull request #158
Opened 2020-02-24 21:23 UTC by PrivacyGeek1337

Request to add Riskified to the blocked list. Beacon fingerprinting script used by many merchants like https://www.canadagoose.com/. Riskified uses this information to identity a user across multiple websites.

![Screenshot 2020-02-24 at 21 22 26](https://user-images.githubusercontent.com/61435352/75192265-cc4d4080-574b-11ea-9335-27ef15a04354.png)

2020-04-30 17:02 UTC, patjack commented
@PrivacyGeek1337  thank you for your detailed issue and corresponding PR! We are in the process of verifying and will update when we have completed review.

2021-04-26 01:20 UTC, KingFlash approved these changes

2021-05-01 05:55 UTC, benkaday3218 approved these changes

2021-05-08 13:09 UTC, janik302 requested changes
Please realize this review thanks

2022-07-01 07:13 UTC, RazpBerryIce reviewed
why am i  a risk on runscape i found a bug i told them i showed them they laught at me and didnt want information on money launders that got drunk and told me to much.
i showed thjem the bug i proved it and then even after it they scammed me by cheating wtf.jagex dont even know and i cant even appeal it its fucken stupid. i deserve an appeal they chain ban me for helping thats bthe most messed up thing i heard. i also told one of the mods to stop being narsacistic. and then i said who scammed me and he lied like a kid and said nobody. after telling him to stop being a child and narcasist one of the other mods in the discord voice chat said it was him. so explain to me how im the bad person? on my page it writes perm manual ban(ban) nothign else thats not a reason and i should be aBLE TO APPEAL IT SOME1 PZL HELP ME OUT U FIX IT IL GIVE U 150 aUSTRALIAN DOLLARS NO BS. ALSO THE PLAYER MOD SAID HIS UNCLE WAS A GMOD AND THAT HE WAS GOING TO GET HIM TO BAN ME THATS ABUSE OF POWER AND AGAISNT THERE RULES I HAVE PROOF OF THIS AND WHICH DISCORD SERVER IT HAPPENED IN. I SHOULD JUST SUE BECUASE I HAD JUST PAID FOR MY MEMBERSHIP. NOT TO MENTION BOUGHT 1K WORTH OF STORE ITEMS....

<html>
<body>
<!--StartFragment-->

  | <!DOCTYPE html><html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><title>RuneScape \| Old School RuneScape</title><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Sign up to RuneScape today and access more than 150 incredible story arcs, new skills, play 20 awesome minigames, construct your own amazing home, and more."><meta name="author" content="Jagex"><style>@font-face{font-family:MuseoSans;src:url(data:application/x-font-woff;bas" alt="RuneScape Logo" title="RuneScape"></div><div><div class="cf-error-details cf-error-1020">
  <h1>Access denied</h1>
  <p>You do not have access to secure.runescape.com.</p><p>The site owner may have set restrictions that prevent you from accessing the site. Contact the site owner for access or try loading the page again.</p>
  <ul class="cferror_details">
    <li>Ray ID: 723d1cefefa0aade</li>
    <li>Timestamp: 2022-07-01 06:33:56 UTC</li>
    <li>Your IP address: 54.79.109.231</li>
    <li class="XXX_no_wrap_overflow_hidden">Requested URL: secure.runescape.com/m=weblogin/loginform.ws?mod=www&amp;ssl=1&amp;expired=0&amp;dest=account_settings </li>
    <li>Error reference number: 1020</li>
    <li>Server ID: FL_493F162</li>
    <li>Server ID: FL_493F162</li>
    <li>Server ID: FL_493F162</li>
    <li>User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36 Edg/103.0.1264.44</li>
  </ul>
</div>
<div><a href="https://support.runescape.com/hc/en-gb/articles/360018322517">Find possible solutions to this problem</a></div></div></div></div></main><script type="text/javascript">(function(){window['__CF$cv$params']={r:'723d1cefefa0aade',m:'SvaPfFYXecasHKFWbOoLth5oxisbO83Sj_iirGDoQms-1656657236-0-AUpzVSXEkzoKnCinuLmtGXfiX3KMMnHYSvl5zRvq7ldIJXHXsu3TJFKRtYon2yDcPch1iACLMlZE9+sk7LltG9/GaTwCyNmgXPNkAv96wLOswt1//6Z1+lQu3ZfjXW7gbyF1Bstv7KgxAiN2+y/6JU+dicTs9ynuqLwRCgmB7jw5A0aVdF7dhhXJ+fTUpvxi5DPYXvjKYIr0nVCboOg/Msg=',s:[0x26fa75d6db,0x4779388195],}})();</script></body></html>

2022-08-10 19:41 UTC, spirillen commented
> @patjack time to close this. Obviously you haven't reviewed this for a year.

@llacb47  it is still relevant to get blocked

2023-05-01 19:49 UTC, closed without merging