Add e.gg to list of Facebook properties.
disconnectme/disconnect-tracking-protection pull request #222
Opened 2020-07-28 23:12 UTC by tvald

Similar to changes in #104 and #127, this adds a first-party Facebook property.

2020-07-29 00:04 UTC, englehardt commented
@patjack This causes breakage in Firefox. See [Bug 1655865](https://bugzilla.mozilla.org/show_bug.cgi?id=1655865)

2020-07-29 00:51 UTC, patjack commented
@tvald thanks for the PR and flagging this. We'll add this on our side shortly. @englehardt I'll also submit the PR to shavar.

2020-07-29 00:56 UTC, closed without merging

2024-05-14 06:51 UTC, Prettycountrygirl36 requested changes
Stop all hacking on Facebook  and messager

2024-05-14 06:51 UTC, Prettycountrygirl36 commented on entities.json
> -}
[]()stop all hacking